local v = vim.opt

v.guifont = "CaskaydiaCove NFM:h8"
v.showmode = false
v.showcmd = true
v.cursorline = false
v.title = false
v.titlestring = ""
v.syntax = "on"
v.number = true
v.relativenumber = true
v.termguicolors = true
v.signcolumn = "yes"
v.cmdheight = 1
v.wildmenu = true
v.backup = false
v.swapfile = false
v.writebackup = false
v.history = 50
v.undolevels = 1000
v.updatetime = 300
v.copyindent = true
v.autowrite = true
v.autoread = true
v.incsearch = true
v.ignorecase = true
v.smartcase = true
v.smartindent = true
v.wrap = false
v.scrolloff = 1
v.completeopt = { "menuone", "noselect" }
v.encoding = "utf-8"
v.fileencoding = "utf-8"
v.autoindent = true
v.expandtab = true
v.tabstop = 4
v.softtabstop = 4
v.shiftwidth = 4
v.backspace = "indent,eol,start"
v.smarttab = true
v.clipboard = "unnamedplus"
v.conceallevel = 0
v.mouse = "a"
v.hlsearch = true
v.pumheight = 10
v.pumblend = 10
v.splitbelow = true
v.splitright = true
v.undofile = true
v.timeoutlen = 1000
v.laststatus = 3
v.ruler = false
v.numberwidth = 4
v.sidescrolloff = 8
v.cursorline = true

vim.g.icons_enabled = true
vim.g.loaded_netrwPlugin = 1
vim.g.loaded_netrw = 1
vim.o.fillchars = [[vert: ,eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]
vim.scriptencoding = "utf-8"
vim.termeconfing = "utf-8"
