require("core.settings")
require("core.autocmds")
require("core.neovide")

-- any comment
require("plugins.lazy")
require("plugins.config.colorscheme")
require("plugins.config.webdevicons")
require("plugins.config.lualine")
require("plugins.config.neotree")
require("plugins.config.treesitter")
require("plugins.config.nvim-notify")
require("plugins.config.window-picker")
require("plugins.config.gitsigns")
require("plugins.config.telescope")
require("plugins.config.autopairs")
require("plugins.config.auto-indent")
require("plugins.config.autotag")
require("plugins.config.chatgpt")
require("plugins.config.local-highlight")
require("plugins.config.indent-blankline")
require("plugins.config.nvim-ufo")
require("plugins.config.template-string")
require("plugins.config.url-open")
require("plugins.config.ccc")

require("plugins.config.lsp")
require("plugins.config.lspsaga")
require("plugins.config.cmp")

require("core.colorscheme")
require("core.keymaps")
